- item_type: PORTS
  ports_list:
    - port: '80'
    - port: '1433'
    - port: '53'
- item_type: SERVICES
  service_list:
    - name: TCP
    - name: TCP_SQL
    - name: UDP
- item_type: NODE
  node_id: '1'
  name: CLIENT_1
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.10.11
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
    - name: UDP
      port: '53'
      state: GOOD
- item_type: NODE
  node_id: '2'
  name: CLIENT_2
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.10.12
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '3'
  name: SWITCH_1
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.10.1
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '4'
  name: SECURITY_SUITE
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.10
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
    - name: UDP
      port: '53'
      state: GOOD
- item_type: NODE
  node_id: '5'
  name: MANAGEMENT_CONSOLE
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.12
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
    - name: UDP
      port: '53'
      state: GOOD
- item_type: NODE
  node_id: '6'
  name: SWITCH_2
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.2.1
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '7'
  name: WEB_SERVER
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.2.10
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
    - name: TCP_SQL
      port: '1433'
      state: GOOD
- item_type: NODE
  node_id: '8'
  name: DATABASE_SERVER
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.2.14
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
    - name: TCP_SQL
      port: '1433'
      state: GOOD
    - name: UDP
      port: '53'
      state: GOOD
- item_type: NODE
  node_id: '9'
  name: BACKUP_SERVER
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.2.16
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: LINK
  id: '10'
  name: LINK_1
  bandwidth: 1000000000
  source: '1'
  destination: '3'
- item_type: LINK
  id: '11'
  name: LINK_2
  bandwidth: 1000000000
  source: '2'
  destination: '3'
- item_type: LINK
  id: '12'
  name: LINK_3
  bandwidth: 1000000000
  source: '3'
  destination: '4'
- item_type: LINK
  id: '13'
  name: LINK_4
  bandwidth: 1000000000
  source: '3'
  destination: '5'
- item_type: LINK
  id: '14'
  name: LINK_5
  bandwidth: 1000000000
  source: '4'
  destination: '6'
- item_type: LINK
  id: '15'
  name: LINK_6
  bandwidth: 1000000000
  source: '5'
  destination: '6'
- item_type: LINK
  id: '16'
  name: LINK_7
  bandwidth: 1000000000
  source: '6'
  destination: '7'
- item_type: LINK
  id: '17'
  name: LINK_8
  bandwidth: 1000000000
  source: '6'
  destination: '8'
- item_type: LINK
  id: '18'
  name: LINK_9
  bandwidth: 1000000000
  source: '6'
  destination: '9'
- item_type: GREEN_IER
  id: '19'
  start_step: 1
  end_step: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '7'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '20'
  start_step: 1
  end_step: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '7'
  destination: '1'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '21'
  start_step: 1
  end_step: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '7'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '22'
  start_step: 1
  end_step: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '7'
  destination: '2'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '23'
  start_step: 1
  end_step: 256
  load: 5000
  protocol: TCP_SQL
  port: '1433'
  source: '7'
  destination: '8'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '24'
  start_step: 1
  end_step: 256
  load: 100000
  protocol: TCP_SQL
  port: '1433'
  source: '8'
  destination: '7'
  mission_criticality: 5
- item_type: GREEN_IER
  id: '25'
  start_step: 1
  end_step: 256
  load: 50000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '9'
  mission_criticality: 2
- item_type: GREEN_IER
  id: '26'
  start_step: 1
  end_step: 256
  load: 50000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '9'
  mission_criticality: 2
- item_type: GREEN_IER
  id: '27'
  start_step: 1
  end_step: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '5'
  destination: '7'
  mission_criticality: 1
- item_type: GREEN_IER
  id: '28'
  start_step: 1
  end_step: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '7'
  destination: '5'
  mission_criticality: 1
- item_type: GREEN_IER
  id: '29'
  start_step: 1
  end_step: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '5'
  destination: '8'
  mission_criticality: 1
- item_type: GREEN_IER
  id: '30'
  start_step: 1
  end_step: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '8'
  destination: '5'
  mission_criticality: 1
- item_type: GREEN_IER
  id: '31'
  start_step: 1
  end_step: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '5'
  destination: '9'
  mission_criticality: 1
- item_type: GREEN_IER
  id: '32'
  start_step: 1
  end_step: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '9'
  destination: '5'
  mission_criticality: 1
- item_type: ACL_RULE
  id: '33'
  permission: ALLOW
  source: 192.168.10.11
  destination: 192.168.2.10
  protocol: ANY
  port: ANY
  position: 0
- item_type: ACL_RULE
  id: '34'
  permission: ALLOW
  source: 192.168.10.11
  destination: 192.168.2.14
  protocol: ANY
  port: ANY
  position: 1
- item_type: ACL_RULE
  id: '35'
  permission: ALLOW
  source: 192.168.10.12
  destination: 192.168.2.14
  protocol: ANY
  port: ANY
  position: 2
- item_type: ACL_RULE
  id: '36'
  permission: ALLOW
  source: 192.168.10.12
  destination: 192.168.2.10
  protocol: ANY
  port: ANY
  position: 3
- item_type: ACL_RULE
  id: '37'
  permission: ALLOW
  source: 192.168.2.10
  destination: 192.168.10.11
  protocol: ANY
  port: ANY
  position: 4
- item_type: ACL_RULE
  id: '38'
  permission: ALLOW
  source: 192.168.2.10
  destination: 192.168.10.12
  protocol: ANY
  port: ANY
  position: 5
- item_type: ACL_RULE
  id: '39'
  permission: ALLOW
  source: 192.168.2.10
  destination: 192.168.2.14
  protocol: ANY
  port: ANY
  position: 6
- item_type: ACL_RULE
  id: '40'
  permission: ALLOW
  source: 192.168.2.14
  destination: 192.168.2.10
  protocol: ANY
  port: ANY
  position: 7
- item_type: ACL_RULE
  id: '41'
  permission: ALLOW
  source: 192.168.10.11
  destination: 192.168.2.16
  protocol: ANY
  port: ANY
  position: 8
- item_type: ACL_RULE
  id: '42'
  permission: ALLOW
  source: 192.168.10.12
  destination: 192.168.2.16
  protocol: ANY
  port: ANY
  position: 9
- item_type: ACL_RULE
  id: '43'
  permission: ALLOW
  source: 192.168.1.12
  destination: 192.168.2.10
  protocol: ANY
  port: ANY
  position: 10
- item_type: ACL_RULE
  id: '44'
  permission: ALLOW
  source: 192.168.1.12
  destination: 192.168.2.14
  protocol: ANY
  port: ANY
  position: 11
- item_type: ACL_RULE
  id: '45'
  permission: ALLOW
  source: 192.168.1.12
  destination: 192.168.2.16
  protocol: ANY
  port: ANY
  position: 12
- item_type: ACL_RULE
  id: '46'
  permission: ALLOW
  source: 192.168.2.10
  destination: 192.168.1.12
  protocol: ANY
  port: ANY
  position: 13
- item_type: ACL_RULE
  id: '47'
  permission: ALLOW
  source: 192.168.2.14
  destination: 192.168.1.12
  protocol: ANY
  port: ANY
  position: 14
- item_type: ACL_RULE
  id: '48'
  permission: ALLOW
  source: 192.168.2.16
  destination: 192.168.1.12
  protocol: ANY
  port: ANY
  position: 15
- item_type: ACL_RULE
  id: '49'
  permission: DENY
  source: ANY
  destination: ANY
  protocol: ANY
  port: ANY
  position: 16
- item_type: RED_POL
  id: '50'
  start_step: 50
  end_step: 50
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: UDP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '51'
  start_step: 75
  end_step: 105
  load: 10000
  protocol: UDP
  port: '53'
  source: '1'
  destination: '8'
  mission_criticality: 0
- item_type: RED_POL
  id: '52'
  start_step: 100
  end_step: 100
  targetNodeId: '8'
  initiator: IER
  type: SERVICE
  protocol: UDP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_POL
  id: '53'
  start_step: 105
  end_step: 105
  targetNodeId: '8'
  initiator: SERVICE
  type: FILE
  protocol: NA
  state: CORRUPT
  sourceNodeId: '8'
  sourceNodeService: UDP
  sourceNodeServiceState: COMPROMISED
- item_type: RED_POL
  id: '54'
  start_step: 105
  end_step: 105
  targetNodeId: '8'
  initiator: SERVICE
  type: SERVICE
  protocol: TCP_SQL
  state: COMPROMISED
  sourceNodeId: '8'
  sourceNodeService: UDP
  sourceNodeServiceState: COMPROMISED
- item_type: RED_POL
  id: '55'
  start_step: 125
  end_step: 125
  targetNodeId: '7'
  initiator: SERVICE
  type: SERVICE
  protocol: TCP
  state: OVERWHELMED
  sourceNodeId: '8'
  sourceNodeService: TCP_SQL
  sourceNodeServiceState: COMPROMISED
