- item_type: PORTS
  ports_list:
    - port: '80'
- item_type: SERVICES
  service_list:
    - name: TCP
- item_type: NODE
  node_id: '1'
  name: PC1
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.2
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '2'
  name: SERVER
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.3
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '3'
  name: PC2
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.4
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '4'
  name: SWITCH1
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.5
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '5'
  name: SWITCH2
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.6
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '6'
  name: SWITCH3
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.7
  software_state: GOOD
  file_system_state: GOOD
- item_type: LINK
  id: '7'
  name: link1
  bandwidth: 1000000000
  source: '1'
  destination: '4'
- item_type: LINK
  id: '8'
  name: link2
  bandwidth: 1000000000
  source: '4'
  destination: '2'
- item_type: LINK
  id: '9'
  name: link3
  bandwidth: 1000000000
  source: '2'
  destination: '5'
- item_type: LINK
  id: '10'
  name: link4
  bandwidth: 1000000000
  source: '2'
  destination: '6'
- item_type: LINK
  id: '11'
  name: link5
  bandwidth: 1000000000
  source: '5'
  destination: '3'
- item_type: LINK
  id: '12'
  name: link6
  bandwidth: 1000000000
  source: '6'
  destination: '3'
- item_type: GREEN_IER
  id: '13'
  start_step: 1
  end_step: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '3'
  destination: '2'
  mission_criticality: 5
- item_type: RED_POL
  id: '14'
  start_step: 50
  end_step: 50
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '15'
  start_step: 60
  end_step: 100
  load: 1000000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '2'
  mission_criticality: 0
- item_type: RED_POL
  id: '16'
  start_step: 80
  end_step: 80
  targetNodeId: '2'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: ACL_RULE
  id: '17'
  permission: ALLOW
  source: ANY
  destination: ANY
  protocol: ANY
  port: ANY
