- item_type: ACTIONS
  type: NODE
- item_type: STEPS
  steps: 256
- item_type: PORTS
  ports_list:
    - port: '80'
- item_type: SERVICES
  service_list:
    - name: TCP
- item_type: NODE
  node_id: '1'
  name: PC1
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.2
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '2'
  name: PC2
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.3
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: NODE
  node_id: '3'
  name: SWITCH1
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.1
  software_state: GOOD
  file_system_state: GOOD
- item_type: NODE
  node_id: '4'
  name: SERVER1
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.4
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- item_type: LINK
  id: '5'
  name: link1
  bandwidth: 1000000000
  source: '1'
  destination: '3'
- item_type: LINK
  id: '6'
  name: link2
  bandwidth: 1000000000
  source: '2'
  destination: '3'
- item_type: LINK
  id: '7'
  name: link3
  bandwidth: 1000000000
  source: '3'
  destination: '4'
- item_type: GREEN_IER
  id: '8'
  start_step: 1
  end_step: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '4'
  mission_criticality: 1
- item_type: GREEN_IER
  id: '9'
  start_step: 1
  end_step: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '4'
  mission_criticality: 1
- item_type: GREEN_IER
  id: '10'
  start_step: 1
  end_step: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '4'
  destination: '2'
  mission_criticality: 5
- item_type: ACL_RULE
  id: '11'
  permission: ALLOW
  source: 192.168.1.2
  destination: 192.168.1.4
  protocol: TCP
  port: 80
- item_type: ACL_RULE
  id: '12'
  permission: ALLOW
  source: 192.168.1.3
  destination: 192.168.1.4
  protocol: TCP
  port: 80
- item_type: ACL_RULE
  id: '13'
  permission: ALLOW
  source: 192.168.1.4
  destination: 192.168.1.3
  protocol: TCP
  port: 80
- item_type: RED_POL
  id: '14'
  start_step: 20
  end_step: 20
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- item_type: RED_IER
  id: '15'
  start_step: 30
  end_step: 256
  load: 10000000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '4'
  mission_criticality: 0
- item_type: RED_POL
  id: '16'
  start_step: 40
  end_step: 40
  targetNodeId: '4'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: OVERWHELMED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
