- itemType: ACTIONS
  type: NODE
- itemType: STEPS
  steps: 256
- itemType: PORTS
  portsList:
  - port: '80'
  - port: '1433'
  - port: '53'
- itemType: SERVICES
  serviceList:
  - name: TCP
  - name: TCP_SQL
  - name: UDP
- itemType: NODE
  id: '1'
  name: CLIENT_1
  baseType: SERVICE
  nodeType: COMPUTER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.10.11
  softwareState: GOOD
  fileSystemState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
  - name: UDP
    port: '53'
    state: GOOD
- itemType: NODE
  id: '2'
  name: CLIENT_2
  baseType: SERVICE
  nodeType: COMPUTER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.10.12
  softwareState: GOOD
  fileSystemState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: NODE
  id: '3'
  name: SWITCH_1
  baseType: ACTIVE
  nodeType: SWITCH
  priority: P2
  hardwareState: 'ON'
  ipAddress: 192.168.10.1
  softwareState: GOOD
  fileSystemState: GOOD
- itemType: NODE
  id: '4'
  name: SECURITY_SUITE
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.1.10
  softwareState: GOOD
  fileSystemState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
  - name: UDP
    port: '53'
    state: GOOD
- itemType: NODE
  id: '5'
  name: MANAGEMENT_CONSOLE
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.1.12
  softwareState: GOOD
  fileSystemState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
  - name: UDP
    port: '53'
    state: GOOD
- itemType: NODE
  id: '6'
  name: SWITCH_2
  baseType: ACTIVE
  nodeType: SWITCH
  priority: P2
  hardwareState: 'ON'
  ipAddress: 192.168.2.1
  softwareState: GOOD
  fileSystemState: GOOD
- itemType: NODE
  id: '7'
  name: WEB_SERVER
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.2.10
  softwareState: GOOD
  fileSystemState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
  - name: TCP_SQL
    port: '1433'
    state: GOOD
- itemType: NODE
  id: '8'
  name: DATABASE_SERVER
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.2.14
  softwareState: GOOD
  fileSystemState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
  - name: TCP_SQL
    port: '1433'
    state: GOOD
  - name: UDP
    port: '53'
    state: GOOD
- itemType: NODE
  id: '9'
  name: BACKUP_SERVER
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.2.16
  softwareState: GOOD
  fileSystemState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: LINK
  id: '10'
  name: LINK_1
  bandwidth: 1000000000
  source: '1'
  destination: '3'
- itemType: LINK
  id: '11'
  name: LINK_2
  bandwidth: 1000000000
  source: '2'
  destination: '3'
- itemType: LINK
  id: '12'
  name: LINK_3
  bandwidth: 1000000000
  source: '3'
  destination: '4'
- itemType: LINK
  id: '13'
  name: LINK_4
  bandwidth: 1000000000
  source: '3'
  destination: '5'
- itemType: LINK
  id: '14'
  name: LINK_5
  bandwidth: 1000000000
  source: '4'
  destination: '6'
- itemType: LINK
  id: '15'
  name: LINK_6
  bandwidth: 1000000000
  source: '5'
  destination: '6'
- itemType: LINK
  id: '16'
  name: LINK_7
  bandwidth: 1000000000
  source: '6'
  destination: '7'
- itemType: LINK
  id: '17'
  name: LINK_8
  bandwidth: 1000000000
  source: '6'
  destination: '8'
- itemType: LINK
  id: '18'
  name: LINK_9
  bandwidth: 1000000000
  source: '6'
  destination: '9'
- itemType: GREEN_IER
  id: '19'
  startStep: 1
  endStep: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '7'
  missionCriticality: 5
- itemType: GREEN_IER
  id: '20'
  startStep: 1
  endStep: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '7'
  destination: '1'
  missionCriticality: 5
- itemType: GREEN_IER
  id: '21'
  startStep: 1
  endStep: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '7'
  missionCriticality: 5
- itemType: GREEN_IER
  id: '22'
  startStep: 1
  endStep: 256
  load: 10000
  protocol: TCP
  port: '80'
  source: '7'
  destination: '2'
  missionCriticality: 5
- itemType: GREEN_IER
  id: '23'
  startStep: 1
  endStep: 256
  load: 5000
  protocol: TCP_SQL
  port: '1433'
  source: '7'
  destination: '8'
  missionCriticality: 5
- itemType: GREEN_IER
  id: '24'
  startStep: 1
  endStep: 256
  load: 100000
  protocol: TCP_SQL
  port: '1433'
  source: '8'
  destination: '7'
  missionCriticality: 5
- itemType: GREEN_IER
  id: '25'
  startStep: 1
  endStep: 256
  load: 50000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '9'
  missionCriticality: 2
- itemType: GREEN_IER
  id: '26'
  startStep: 1
  endStep: 256
  load: 50000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '9'
  missionCriticality: 2
- itemType: GREEN_IER
  id: '27'
  startStep: 1
  endStep: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '5'
  destination: '7'
  missionCriticality: 1
- itemType: GREEN_IER
  id: '28'
  startStep: 1
  endStep: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '7'
  destination: '5'
  missionCriticality: 1
- itemType: GREEN_IER
  id: '29'
  startStep: 1
  endStep: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '5'
  destination: '8'
  missionCriticality: 1
- itemType: GREEN_IER
  id: '30'
  startStep: 1
  endStep: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '8'
  destination: '5'
  missionCriticality: 1
- itemType: GREEN_IER
  id: '31'
  startStep: 1
  endStep: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '5'
  destination: '9'
  missionCriticality: 1
- itemType: GREEN_IER
  id: '32'
  startStep: 1
  endStep: 256
  load: 5000
  protocol: TCP
  port: '80'
  source: '9'
  destination: '5'
  missionCriticality: 1
- itemType: ACL_RULE
  id: '33'
  permission: ALLOW
  source: 192.168.10.11
  destination: 192.168.2.10
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '34'
  permission: ALLOW
  source: 192.168.10.11
  destination: 192.168.2.14
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '35'
  permission: ALLOW
  source: 192.168.10.12
  destination: 192.168.2.14
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '36'
  permission: ALLOW
  source: 192.168.10.12
  destination: 192.168.2.10
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '37'
  permission: ALLOW
  source: 192.168.2.10
  destination: 192.168.10.11
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '38'
  permission: ALLOW
  source: 192.168.2.10
  destination: 192.168.10.12
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '39'
  permission: ALLOW
  source: 192.168.2.10
  destination: 192.168.2.14
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '40'
  permission: ALLOW
  source: 192.168.2.14
  destination: 192.168.2.10
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '41'
  permission: ALLOW
  source: 192.168.10.11
  destination: 192.168.2.16
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '42'
  permission: ALLOW
  source: 192.168.10.12
  destination: 192.168.2.16
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '43'
  permission: ALLOW
  source: 192.168.1.12
  destination: 192.168.2.10
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '44'
  permission: ALLOW
  source: 192.168.1.12
  destination: 192.168.2.14
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '45'
  permission: ALLOW
  source: 192.168.1.12
  destination: 192.168.2.16
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '46'
  permission: ALLOW
  source: 192.168.2.10
  destination: 192.168.1.12
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '47'
  permission: ALLOW
  source: 192.168.2.14
  destination: 192.168.1.12
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '48'
  permission: ALLOW
  source: 192.168.2.16
  destination: 192.168.1.12
  protocol: ANY
  port: ANY
- itemType: ACL_RULE
  id: '49'
  permission: DENY
  source: ANY
  destination: ANY
  protocol: ANY
  port: ANY
- itemType: RED_POL
  id: '50'
  startStep: 50
  endStep: 50
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: UDP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- itemType: RED_IER
  id: '51'
  startStep: 75
  endStep: 105
  load: 10000
  protocol: UDP
  port: '53'
  source: '1'
  destination: '8'
  missionCriticality: 0
- itemType: RED_POL
  id: '52'
  startStep: 100
  endStep: 100
  targetNodeId: '8'
  initiator: IER
  type: SERVICE
  protocol: UDP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- itemType: RED_POL
  id: '53'
  startStep: 105
  endStep: 105
  targetNodeId: '8'
  initiator: SERVICE
  type: FILE
  protocol: NA
  state: CORRUPT
  sourceNodeId: '8'
  sourceNodeService: UDP
  sourceNodeServiceState: COMPROMISED
- itemType: RED_POL
  id: '54'
  startStep: 105
  endStep: 105
  targetNodeId: '8'
  initiator: SERVICE
  type: SERVICE
  protocol: TCP_SQL
  state: COMPROMISED
  sourceNodeId: '8'
  sourceNodeService: UDP
  sourceNodeServiceState: COMPROMISED
- itemType: RED_POL
  id: '55'
  startStep: 125
  endStep: 125
  targetNodeId: '7'
  initiator: SERVICE
  type: SERVICE
  protocol: TCP
  state: OVERWHELMED
  sourceNodeId: '8'
  sourceNodeService: TCP_SQL 
  sourceNodeServiceState: COMPROMISED