- itemType: ACTIONS
  type: NODE
- itemType: OBSERVATION_SPACE
  components:
    - name: NODE_LINK_TABLE
    - name: NODE_STATUSES
    - name: LINK_TRAFFIC_LEVELS
      options:
        - combine_service_traffic : False
        - quantisation_levels : 7
- itemType: STEPS
  steps: 128
- itemType: PORTS
  portsList:
    - port: '80'
- itemType: SERVICES
  serviceList:
    - name: TCP
- itemType: NODE
  node_id: '1'
  name: PC1
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.2
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- itemType: NODE
  node_id: '2'
  name: SERVER
  node_class: SERVICE
  node_type: SERVER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.3
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- itemType: NODE
  node_id: '3'
  name: PC2
  node_class: SERVICE
  node_type: COMPUTER
  priority: P5
  hardware_state: 'ON'
  ip_address: 192.168.1.4
  software_state: GOOD
  file_system_state: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- itemType: NODE
  node_id: '4'
  name: SWITCH1
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.5
  software_state: GOOD
  file_system_state: GOOD
- itemType: NODE
  node_id: '5'
  name: SWITCH2
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.6
  software_state: GOOD
  file_system_state: GOOD
- itemType: NODE
  node_id: '6'
  name: SWITCH3
  node_class: ACTIVE
  node_type: SWITCH
  priority: P2
  hardware_state: 'ON'
  ip_address: 192.168.1.7
  software_state: GOOD
  file_system_state: GOOD
- itemType: LINK
  id: '7'
  name: link1
  bandwidth: 1000000000
  source: '1'
  destination: '4'
- itemType: LINK
  id: '8'
  name: link2
  bandwidth: 1000000000
  source: '4'
  destination: '2'
- itemType: LINK
  id: '9'
  name: link3
  bandwidth: 1000000000
  source: '2'
  destination: '5'
- itemType: LINK
  id: '10'
  name: link4
  bandwidth: 1000000000
  source: '2'
  destination: '6'
- itemType: LINK
  id: '11'
  name: link5
  bandwidth: 1000000000
  source: '5'
  destination: '3'
- itemType: LINK
  id: '12'
  name: link6
  bandwidth: 1000000000
  source: '6'
  destination: '3'
- itemType: GREEN_IER
  id: '13'
  startStep: 1
  endStep: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '3'
  destination: '2'
  missionCriticality: 5
- itemType: RED_POL
  id: '14'
  startStep: 50
  endStep: 50
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- itemType: RED_IER
  id: '15'
  startStep: 60
  endStep: 100
  load: 1000000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '2'
  missionCriticality: 0
- itemType: RED_POL
  id: '16'
  startStep: 80
  endStep: 80
  targetNodeId: '2'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- itemType: ACL_RULE
  id: '17'
  permission: ALLOW
  source: ANY
  destination: ANY
  protocol: ANY
  port: ANY
