- itemType: ACTIONS
  type: NODE
- itemType: STEPS
  steps: 128
- itemType: PORTS
  portsList:
    - port: '80'
- itemType: SERVICES
  serviceList:
    - name: TCP
- itemType: NODE
  id: '1'
  name: PC1
  baseType: SERVICE
  nodeType: COMPUTER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.1.2
  softwareState: GOOD
  fileSystemState: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- itemType: NODE
  id: '2'
  name: SERVER
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.1.3
  softwareState: GOOD
  fileSystemState: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- itemType: NODE
  id: '3'
  name: PC2
  baseType: SERVICE
  nodeType: COMPUTER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.1.4
  softwareState: GOOD
  fileSystemState: GOOD
  services:
    - name: TCP
      port: '80'
      state: GOOD
- itemType: NODE
  id: '4'
  name: SWITCH1
  baseType: ACTIVE
  nodeType: SWITCH
  priority: P2
  hardwareState: 'ON'
  ipAddress: 192.168.1.5
  softwareState: GOOD
  fileSystemState: GOOD
- itemType: NODE
  id: '5'
  name: SWITCH2
  baseType: ACTIVE
  nodeType: SWITCH
  priority: P2
  hardwareState: 'ON'
  ipAddress: 192.168.1.6
  softwareState: GOOD
  fileSystemState: GOOD
- itemType: NODE
  id: '6'
  name: SWITCH3
  baseType: ACTIVE
  nodeType: SWITCH
  priority: P2
  hardwareState: 'ON'
  ipAddress: 192.168.1.7
  softwareState: GOOD
  fileSystemState: GOOD
- itemType: LINK
  id: '7'
  name: link1
  bandwidth: 1000000000
  source: '1'
  destination: '4'
- itemType: LINK
  id: '8'
  name: link2
  bandwidth: 1000000000
  source: '4'
  destination: '2'
- itemType: LINK
  id: '9'
  name: link3
  bandwidth: 1000000000
  source: '2'
  destination: '5'
- itemType: LINK
  id: '10'
  name: link4
  bandwidth: 1000000000
  source: '2'
  destination: '6'
- itemType: LINK
  id: '11'
  name: link5
  bandwidth: 1000000000
  source: '5'
  destination: '3'
- itemType: LINK
  id: '12'
  name: link6
  bandwidth: 1000000000
  source: '6'
  destination: '3'
- itemType: GREEN_IER
  id: '13'
  startStep: 1
  endStep: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '3'
  destination: '2'
  missionCriticality: 5
- itemType: RED_POL
  id: '14'
  startStep: 50
  endStep: 50
  targetNodeId: '1'
  initiator: DIRECT
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- itemType: RED_IER
  id: '15'
  startStep: 60
  endStep: 100
  load: 1000000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '2'
  missionCriticality: 0
- itemType: RED_POL
  id: '16'
  startStep: 80
  endStep: 80
  targetNodeId: '2'
  initiator: IER
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  sourceNodeId: NA
  sourceNodeService: NA
  sourceNodeServiceState: NA
- itemType: ACL_RULE
  id: '17'
  permission: ALLOW
  source: ANY
  destination: ANY
  protocol: ANY
  port: ANY
