agents: &greens
  - ref: green_B
    team: GREEN
    type: ProbabilisticAgent
    agent_settings:
      action_probabilities:
        0: 0.95
        1: 0.05
    observation_space: null
    action_space:
      action_map:
        0:
          action: DONOTHING
          options: {}
        1:
          action: NODE_APPLICATION_EXECUTE
          options:
            node_id: 0
            application_id: 0

    reward_function:
      reward_components:
        - type: GREEN_ADMIN_DATABASE_UNREACHABLE_PENALTY
          weight: 1.0
          options:
            node_hostname: client
