agents: &greens
  - ref: green_A
    team: GREEN
    type: ProbabilisticAgent
    agent_settings:
      action_probabilities:
        0: 0.2
        1: 0.8
    observation_space: null
    action_space:
      action_list:
        - type: DONOTHING
        - type: NODE_APPLICATION_EXECUTE
      options:
        nodes:
        - node_name: client
          applications:
            - application_name: DatabaseClient
      action_map:
        0:
          action: DONOTHING
          options: {}
        1:
          action: NODE_APPLICATION_EXECUTE
          options:
            node_id: 0
            application_id: 0

    reward_function:
      reward_components:
        - type: GREEN_ADMIN_DATABASE_UNREACHABLE_PENALTY
          weight: 1.0
          options:
            node_hostname: client
