agents: &greens
  - ref: green_A
    team: GREEN
    type: ProbabilisticAgent
    agent_settings:
      action_probabilities:
        0: 0.2
        1: 0.8

    action_space:
      action_map:
        0:
          action: do_nothing
          options: {}
        1:
          action: node_application_execute
          options:
            node_name: client
            application_name: DatabaseClient

    reward_function:
      reward_components:
        - type: GREEN_ADMIN_DATABASE_UNREACHABLE_PENALTY
          weight: 1.0
          options:
            node_hostname: client
