reds: &reds
  - ref: red_A
    team: RED
    type: RedDatabaseCorruptingAgent

    agent_settings:
      possible_start_nodes: [client,]
      target_application: DataManipulationBot
      start_step: 10
      frequency: 10
      variance: 0
