reds: &reds
  - ref: attacker_1
    team: RED
    type: RedDatabaseCorruptingAgent

    observation_space: null

    action_space:
      action_list:
        - type: DONOTHING
        - type: NODE_APPLICATION_EXECUTE
      options:
        nodes:
        - node_name: client_1
          applications:
            - application_name: DataManipulationBot
        - node_name: client_2
          applications:
            - application_name: DataManipulationBot
        max_folders_per_node: 1
        max_files_per_folder: 1
        max_services_per_node: 1

    reward_function:
      reward_components:
        - type: DUMMY

    agent_settings: # options specific to this particular agent type, basically args of __init__(self)
      start_settings:
        start_step: 25
        frequency: 20
        variance: 5
