trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:

      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install build
    pip install wheel
    pip install twine
    pip install keyring
    pip install artifacts-keyring
  displayName: 'Install build dependencies'

- script: |
    python setup.py sdist bdist_wheel
  displayName: 'Build PrimAITE sdist and wheel'

- task: TwineAuthenticate@1
  displayName: 'Twine Authenticate'
  inputs:
    artifactFeed: PrimAITE/PrimAITE

- script: |
    python -m twine upload --verbose -r PrimAITE --config-file  $(PYPIRC_PATH) dist/*
  displayName: 'Artifact Upload'
