trigger:
- main

strategy:
  matrix:
    Ubuntu2004Python38:
      python.version: '3.8'
      imageName: 'ubuntu-20.04'
    Ubuntu2004Python39:
      python.version: '3.9'
      imageName: 'ubuntu-20.04'
    Ubuntu2004Python310:
      python.version: '3.10'
      imageName: 'ubuntu-20.04'
    WindowsPython38:
      python.version: '3.8'
      imageName: 'windows-latest'
    WindowsPython39:
      python.version: '3.9'
      imageName: 'windows-latest'
    WindowsPython310:
      python.version: '3.10'
      imageName: 'windows-latest'
    MacPython38:
      python.version: '3.8'
      imageName: 'macOS-latest'
    MacPython39:
      python.version: '3.9'
      imageName: 'macOS-latest'
    MacPython310:
      python.version: '3.10'
      imageName: 'macOS-latest'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip==23.0.1
    pip install wheel==0.38.4 --upgrade
    pip install setuptools==66 --upgrade
    pip install build==0.10.0
    pip install twine
    pip install keyring
    pip install artifacts-keyring
  displayName: 'Install build dependencies'

- script: |
    python -m build
  displayName: 'Build PrimAITE sdist and wheel'

- task: TwineAuthenticate@1
  displayName: 'Twine Authenticate'
  inputs:
    artifactFeed: PrimAITE/PrimAITE

- script: |
    python -m twine upload --verbose -r PrimAITE --config-file  $(PYPIRC_PATH) dist/*.whl
  displayName: 'Artifact Upload'
