trigger:
  branches:
    exclude:
    - '*'
    include:
    - 'refs/heads/release/*'

schedules:
- cron: "0 2 * * 1-5"  # Run at 2 AM every weekday
  displayName: "Weekday Schedule"
  branches:
    include:
    - 'refs/heads/dev'
variables:
  VERSION: ''
  MAJOR_VERSION: ''

jobs:
- job: PrimAITE_Benchmark
  timeoutInMinutes: 360 # 6-hour maximum
  pool:
    vmImage: ubuntu-latest
  workspace:
    clean: all
  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      VERSION=$(cat src/primaite/VERSION | tr -d '\n')
      if [[ "$(Build.SourceBranch)" == "refs/heads/dev" ]]; then
        DATE=$(date +%Y%m%d)
        echo "${VERSION}+dev.${DATE}" > src/primaite/VERSION
      fi
    displayName: 'Update VERSION file for Dev Benchmark'

  - script: |
      VERSION=$(cat src/primaite/VERSION | tr -d '\n')
      MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
      echo "##vso[task.setvariable variable=VERSION]$VERSION"
      echo "##vso[task.setvariable variable=MAJOR_VERSION]$MAJOR_VERSION"
    displayName: 'Set Version Variables'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -e .[dev,rl]
      primaite setup
    displayName: 'Install Dependencies'

  - script: |
      set -e
      cd benchmark
      python3 primaite_benchmark.py
      cd ..
    displayName: 'Run Benchmarking Script'

  - script: |
      git config --global user.email "oss@dstl.gov.uk"
      git config --global user.name "Defence Science and Technology Laboratory UK"
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: 'Configure Git'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))

  - script: |
      git add benchmark/results/v$(MAJOR_VERSION)/v$(VERSION)/*
      git commit -m "Automated benchmark output commit for version $(VERSION)"
      git push origin HEAD:refs/heads/$(Build.SourceBranchName)
    displayName: 'Commit and Push Benchmark Results'
    workingDirectory: $(System.DefaultWorkingDirectory)
    env:
      GIT_CREDENTIALS: $(System.AccessToken)
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))

  - script: |
      tar czf primaite_v$(VERSION)_benchmark.tar.gz benchmark/results/v$(MAJOR_VERSION)/v$(VERSION)
    displayName: 'Prepare Artifacts for Publishing'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: primaite_v$(VERSION)_benchmark.tar.gz
      artifactName: 'benchmark-output'
      publishLocation: 'pipeline'
    displayName: 'Publish Benchmark Output as Artifact'
