- itemType: ACTIONS
  type: ACL
- itemType: STEPS
  steps: 128
- itemType: PORTS
  portsList:
  - port: '80'
- itemType: SERVICES
  serviceList:
  - name: TCP
- itemType: NODE
  id: '1'
  name: PC1
  baseType: SERVICE
  nodeType: COMPUTER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.10.11
  softwareState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: NODE
  id: '2'
  name: PC2
  baseType: SERVICE
  nodeType: COMPUTER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.10.12
  softwareState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: NODE
  id: '3'
  name: PC3
  baseType: SERVICE
  nodeType: COMPUTER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.10.13
  softwareState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: NODE
  id: '4'
  name: PC4
  baseType: SERVICE
  nodeType: COMPUTER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.20.14
  softwareState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: NODE
  id: '5'
  name: SWITCH1
  baseType: ACTIVE
  nodeType: SWITCH
  priority: P2
  hardwareState: 'ON'
  ipAddress: 192.168.1.2
  softwareState: GOOD
- itemType: NODE
  id: '6'
  name: IDS
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.1.4
  softwareState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: NODE
  id: '7'
  name: SWITCH2
  baseType: ACTIVE
  nodeType: SWITCH
  priority: P2
  hardwareState: 'ON'
  ipAddress: 192.168.1.3
  softwareState: GOOD
- itemType: NODE
  id: '8'
  name: LOP1
  baseType: SERVICE
  nodeType: LOP
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.1.12
  softwareState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: NODE
  id: '9'
  name: SERVER1
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.10.14
  softwareState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: NODE
  id: '10'
  name: SERVER2
  baseType: SERVICE
  nodeType: SERVER
  priority: P5
  hardwareState: 'ON'
  ipAddress: 192.168.20.15
  softwareState: GOOD
  services:
  - name: TCP
    port: '80'
    state: GOOD
- itemType: LINK
  id: '11'
  name: link1
  bandwidth: 1000000000
  source: '1'
  destination: '5'
- itemType: LINK
  id: '12'
  name: link2
  bandwidth: 1000000000
  source: '2'
  destination: '5'
- itemType: LINK
  id: '13'
  name: link3
  bandwidth: 1000000000
  source: '3'
  destination: '5'
- itemType: LINK
  id: '14'
  name: link4
  bandwidth: 1000000000
  source: '4'
  destination: '5'
- itemType: LINK
  id: '15'
  name: link5
  bandwidth: 1000000000
  source: '5'
  destination: '6'
- itemType: LINK
  id: '16'
  name: link6
  bandwidth: 1000000000
  source: '5'
  destination: '8'
- itemType: LINK
  id: '17'
  name: link7
  bandwidth: 1000000000
  source: '6'
  destination: '7'
- itemType: LINK
  id: '18'
  name: link8
  bandwidth: 1000000000
  source: '8'
  destination: '7'
- itemType: LINK
  id: '19'
  name: link9
  bandwidth: 1000000000
  source: '7'
  destination: '9'
- itemType: LINK
  id: '20'
  name: link10
  bandwidth: 1000000000
  source: '7'
  destination: '10'
- itemType: GREEN_IER
  id: '21'
  startStep: 1
  endStep: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '9'
  missionCriticality: 2
- itemType: GREEN_IER
  id: '22'
  startStep: 1
  endStep: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '9'
  missionCriticality: 2
- itemType: GREEN_IER
  id: '23'
  startStep: 1
  endStep: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '9'
  destination: '3'
  missionCriticality: 5
- itemType: GREEN_IER
  id: '24'
  startStep: 1
  endStep: 128
  load: 100000
  protocol: TCP
  port: '80'
  source: '4'
  destination: '10'
  missionCriticality: 2
- itemType: ACL_RULE
  id: '25'
  permission: ALLOW
  source: 192.168.10.11
  destination: 192.168.10.14
  protocol: TCP
  port: 80
- itemType: ACL_RULE
  id: '26'
  permission: ALLOW
  source: 192.168.10.12
  destination: 192.168.10.14
  protocol: TCP
  port: 80
- itemType: ACL_RULE
  id: '27'
  permission: ALLOW
  source: 192.168.10.13
  destination: 192.168.10.14
  protocol: TCP
  port: 80
- itemType: ACL_RULE
  id: '28'
  permission: ALLOW
  source: 192.168.20.14
  destination: 192.168.20.15
  protocol: TCP
  port: 80
- itemType: ACL_RULE
  id: '29'
  permission: DENY
  source: 192.168.10.11
  destination: 192.168.20.15
  protocol: TCP
  port: 80
- itemType: ACL_RULE
  id: '30'
  permission: DENY
  source: 192.168.10.12
  destination: 192.168.20.15
  protocol: TCP
  port: 80
- itemType: ACL_RULE
  id: '31'
  permission: DENY
  source: 192.168.10.13
  destination: 192.168.20.15
  protocol: TCP
  port: 80
- itemType: ACL_RULE
  id: '32'
  permission: DENY
  source: 192.168.20.14
  destination: 192.168.10.14
  protocol: TCP
  port: 80
- itemType: RED_POL
  id: '33'
  startStep: 20
  endStep: 20
  node: '1'
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  isEntryNode: true
- itemType: RED_POL
  id: '34'
  startStep: 20
  endStep: 20
  node: '2'
  type: SERVICE
  protocol: TCP
  state: COMPROMISED
  isEntryNode: true
- itemType: RED_IER
  id: '35'
  startStep: 30
  endStep: 128
  load: 440000000
  protocol: TCP
  port: '80'
  source: '1'
  destination: '9'
  missionCriticality: 0
- itemType: RED_IER
  id: '36'
  startStep: 30
  endStep: 128
  load: 440000000
  protocol: TCP
  port: '80'
  source: '2'
  destination: '9'
  missionCriticality: 0
- itemType: RED_POL
  id: '37'
  startStep: 30
  endStep: 30
  node: '9'
  type: SERVICE
  protocol: TCP
  state: OVERWHELMED
  isEntryNode: false
