# Main Config File

# Generic config values
# Choose one of these (dependent on Agent being trained)
# "STABLE_BASELINES3_PPO"
# "STABLE_BASELINES3_A2C"
# "GENERIC"
agentIdentifier: STABLE_BASELINES3_PPO
# Maximum number of episodes to run per training session
numEpisodes: 10
# Time delay between steps (for generic agents)
timeDelay: 10
# Filename of the scenario / laydown
configFilename: config_2_DDOS_BASIC.yaml

# Environment config values
# The high value for the observation space
observationSpaceHighValue: 1000000000                   

# Reward values
# Generic
allOk: 0 
# Node Operating State
offShouldBeOn: -10
offShouldBeResetting: -5
onShouldBeOff: -2
onShouldBeResetting: -5
resettingShouldBeOn: -5
resettingShouldBeOff: -2 
# Node O/S or Service State
goodShouldBePatching: 2
goodShouldBeCompromised: 5
goodShouldBeOverwhelmed: 5
patchingShouldBeGood: -5
patchingShouldBeCompromised: 2
patchingShouldBeOverwhelmed: 2
compromisedShouldBeGood: -20
compromisedShouldBePatching: -20
compromisedShouldBeOverwhelmed: -20
compromised: -20     
overwhelmedShouldBeGood: -20
overwhelmedShouldBePatching: -20
overwhelmedShouldBeCompromised: -20
overwhelmed: -20
# IER status
redIerRunning: -5
greenIerBlocked: -10

# Patching / Reset durations
osPatchingDuration: 5                         # The time taken to patch the OS
nodeResetDuration: 5                          # The time taken to reset a node (hardware)
servicePatchingDuration: 5                    # The time taken to patch a service
