# The main PrimAITE application config file

developer_mode:
  enabled: False  # not enabled by default
  sys_log_level: DEBUG # level of output for system logs, DEBUG by default
  agent_log_level: DEBUG # level of output for agent logs, DEBUG by default
  output_agent_logs: False # level of output for system logs, DEBUG by default
  output_sys_logs: False  # system logs not output by default
  output_pcap_logs: False  # pcap logs not output by default
  output_to_terminal: False  # do not output to terminal by default
  output_dir: null  # none by default - none will print to repository root

# Logging
logging:
  log_level: INFO
  logger_format:
    DEBUG: '%(asctime)s: %(message)s'
    INFO: '%(asctime)s: %(message)s'
    WARNING: '%(asctime)s::%(levelname)s::%(name)s::%(lineno)s::%(message)s'
    ERROR: '%(asctime)s::%(levelname)s::%(name)s::%(lineno)s::%(message)s'
    CRITICAL: '%(asctime)s::%(levelname)s::%(name)s::%(lineno)s::%(message)s'
